// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblwFV407-Pl2WIxDEneB4V8Bzl16v1JA',
    appId: '1:669095559063:web:7d7a44c8e33d00bf1eced2',
    messagingSenderId: '669095559063',
    projectId: 'champion-6c444',
    authDomain: 'champion-6c444.firebaseapp.com',
    storageBucket: 'champion-6c444.firebasestorage.app',
    measurementId: 'G-H5HXE2Q5LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRJn9DbN2YNveQpo12F5BjuCMPp0_AKY',
    appId: '1:669095559063:android:2593329a5c51e1761eced2',
    messagingSenderId: '669095559063',
    projectId: 'champion-6c444',
    storageBucket: 'champion-6c444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQI47x33DCfQ47yDXYXkreQiRqh23M7vw',
    appId: '1:669095559063:ios:bf9c8d90c55b7f571eced2',
    messagingSenderId: '669095559063',
    projectId: 'champion-6c444',
    storageBucket: 'champion-6c444.firebasestorage.app',
    iosBundleId: 'com.educationmz.champion.OneSignalNotificationServiceExtension',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQI47x33DCfQ47yDXYXkreQiRqh23M7vw',
    appId: '1:669095559063:ios:b1ef1c91c6a665f01eced2',
    messagingSenderId: '669095559063',
    projectId: 'champion-6c444',
    storageBucket: 'champion-6c444.firebasestorage.app',
    iosBundleId: 'com.educationmz.education',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDblwFV407-Pl2WIxDEneB4V8Bzl16v1JA',
    appId: '1:669095559063:web:7a3cc3ead83de9b61eced2',
    messagingSenderId: '669095559063',
    projectId: 'champion-6c444',
    authDomain: 'champion-6c444.firebaseapp.com',
    storageBucket: 'champion-6c444.firebasestorage.app',
    measurementId: 'G-5BNC93N8B7',
  );

}